---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: databases-credentials
  namespace: pursit
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: kasumi-secret-store
    kind: ClusterSecretStore
  target:
    name: databases-credentials
  data:
    - secretKey: POSTGRES_USERNAME
      remoteRef:
        key: databases-credentials
        property: POSTGRES_USERNAME
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: databases-credentials
        property: POSTGRES_PASSWORD

