PUT https://pursit.ru/backend/sitter
Content-Type: application/json
Cookie: mur=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLQvtC-0L7QvtC-0L7QvtC-0L7QvtC-0L7QvtC-0L7QvtC-0L7QvtC-0L7Rh9C10L3RjCDQtNC70LjQuNC40LjQuNC40LjQuNC40LjQuNC40LjQuNC90L3QvtC1INC40LzRjyIsImlhdCI6MTczMzE1NDY2MCwiZXhwIjoxNzMzMzI3NDYwfQ.JDlHb36eGeChy09hpU8nUYljdqmAb-YrYjznDCiW6bn6tuZi7_2Gn9kEYXXATeS-e_bhjS1eNKuQUAp-qgmnpg

{
  "type": "pet-sitting",
  "name": "Елизавета Б.",
  "avatarUrl": "/cat.png",
  "shortDescription": "Домашняя передержка животных – это размещение питомцев в тех условиях, к которым они привыкли.",
  "longDescription": "Домашняя передержка животных – это размещение питомцев в тех условиях, к которым они привыкли. На фотографиях питомцы, которые хорошо провели время в нашем доме. Такая передержка предлагает помощь хозяевам, планирующим отъезд, отпуск. Это временное жилище для вашей собаки, в котором она не будет испытывать дискомфорт. Опытные руки хозяев передержки найдут подход к вашему питомцу и помогут перенести разлуку. Ждём ваших питомцев у нас в гостях! Люблю животных, опыт в этой сфере большой. Домашняя передержка в загородном доме с 3х либо 4х разовым выгулом на большом участке и в лесу.",
  "price": 700,
  "experience": 1,
  "photosUrls": [],
  "readyComeItself": true,
  "takesCats": false,
  "takesDogs": true,
  "geolocation": {
    "latitude": 0,
    "longitude": 0,
    "name": "Местоположение тестового ситтера 4"
  }
}

###