---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pursit-s3-credentials
  namespace: pursit
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: umu-kv
    kind: ClusterSecretStore
  target:
    name: pursit-s3-credentials
  data:
    - secretKey: S3_URL
      remoteRef:
        key: pursit-secrets
        property: S3_URL
    - secretKey: S3_ACCESS
      remoteRef:
        key: pursit-secrets
        property: S3_ACCESS
    - secretKey: S3_SECRET
      remoteRef:
        key: pursit-secrets
        property: S3_SECRET
    - secretKey: S3_REGION
      remoteRef:
        key: pursit-secrets
        property: S3_REGION
    - secretKey: S3_BUCKET
      remoteRef:
        key: pursit-secrets
        property: S3_BUCKET
