apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pursit-ui
  namespace: pursit
spec:
  destination:
    namespace: pursit
    server: https://kubernetes.default.svc
  source:
    path: iac/kubernetes
    repoURL: git@github.com:umu-art/pursit.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
