pursit:
  auth:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationHours: 48

spring:
  application:
    name: pursit

  datasource:
    url: jdbc:postgresql://postgres.databases.svc.cluster.local:5432/pursit
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    ru: trace

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true