name: "Prepare env"
description: "Подготовка окружения для пайпы, установка java, node"

runs:
  using: "composite"
  steps:
  - name: Set up Node.js 22
    uses: actions/setup-node@v4.0.4
    with:
      node-version: 22
      cache: 'npm'
      cache-dependency-path: |
        front/package-lock.json

  - name: Set up JDK 23
    uses: actions/setup-java@v4
    with:
      java-version: 23
      distribution: 'temurin'
      cache: 'maven'
      cache-dependency-path: |
        core/pom.xml
        media/pom.xml

  - name: Build API
    shell: bash
    run: cd ./api && chmod +x ./build.sh && ./build.sh
