name: "Prepare env"
description: "Подготовка окружения для пайпы, установка java, node"

runs:
  using: "composite"
  steps:
  - name: Set up Node.js 21
    uses: actions/setup-node@v4.0.4
    with:
      node-version: 21
      cache: 'npm'

  - name: Set up JDK 21
    uses: actions/setup-java@v4
    with:
      java-version: 21
      distribution: 'temurin'
      cache: 'maven'

  - name: Build API
    shell: bash
    run: cd ./api && chmod +x ./build.sh && ./build.sh
