apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pursit-ui-ingress
  namespace: pursit
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: pursit.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pursit-ui
                port:
                  name: http
  tls:
    - hosts:
        - pursit.ru
      secretName: pursit-tls
