---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pursit-cdn
  namespace: pursit
  labels:
    app: pursit-cdn
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pursit-cdn
  template:
    metadata:
      name: pursit-cdn
      labels:
        app: pursit-cdn
    spec:
      containers:
        - name: pursit-cdn
          image: ghcr.io/umu-art/pursit-cdn:master
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false

          resources:
            requests:
              memory: "50M"
              cpu: "50m"
            limits:
              memory: "100M"
              cpu: "100m"

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
