---
apiVersion: v1
kind: Service
metadata:
  name: pursit-cdn
  namespace: pursit
spec:
  selector:
    app: pursit-cdn
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
  type: ClusterIP
