name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-front:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/workflows/actions/prepare_env

      - name: Install deps
        working-directory: front
        run: npm install && npm install @rollup/rollup-linux-x64-gnu

      - name: Build front
        working-directory: front
        run: npm run build

      - name: Build docker image
        uses: ./.github/workflows/actions/build_image
        with:
          image: pursit-front
          actor: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set kube context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBESECRET }}

      - name: Kube rollout restart
        run: kubectl rollout restart deployment/pursit-front -n pursit

  deploy-back:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/workflows/actions/prepare_env

      - name: Build back
        working-directory: back
        run: mvn install

      - name: Build docker image
        uses: ./.github/workflows/actions/build_image
        with:
          image: pursit-back
          actor: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set kube context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBESECRET }}

      - name: Kube rollout restart
        run: kubectl rollout restart deployment/pursit-back -n pursit

  argo-sync:
    needs:
      - deploy-front
      - deploy-back

    runs-on: ubuntu-latest

    steps:
      - name: Install argocd
        run: curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64;\
          chmod +x ./argocd-linux-amd64

      - name: Argo sync
        run: ./argocd-linux-amd64 --server argocd.umu-art.ru --grpc-web --auth-token ${{ secrets.ARGO_TOKEN }} app sync pursit --prune --timeout 300
