name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js 22.9.0
      uses: actions/setup-node@v4
      with:
        node-version: 22.9.0

    - name: Install deps
      run: npm install && npm install @rollup/rollup-linux-x64-gnu

    - name: Build
      run: npm run build

    - name: Log in to the Container registry
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.REGISTRY }}/${{ github.actor }}/pursit-ui

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./iac/image/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Set the Kubernetes context
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBESECRET }}
        context: kubernetes-admin@kubernetes

    - name: Deploy
      run: kubectl rollout restart deployment/pursit-ui -n pursit
